/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.extensions.vm.api;

import static java.time.LocalDateTime.now;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Attributes on the message content generated by a VM connector operation
 *
 * @since 1.0
 */
public class VMMessageAttributes implements Serializable {

  private static final long serialVersionUID = 3923721884012142263L;

  /**
   * The name of the queue the content came from.
   */
  private final String queueName;

  /**
   * The correlation id for the message
   */
  private final String correlationId;

  /**
   * The time at which the content was retrieved.
   */
  private final LocalDateTime timestamp = now();

  /**
   * Creates a new instance
   *
   * @param queueName     the name of the queue from which the message was taken
   * @param correlationId the message correlation id
   */
  public VMMessageAttributes(String queueName, String correlationId) {
    this.queueName = queueName;
    this.correlationId = correlationId;
  }

  public String getQueueName() {
    return queueName;
  }

  public String getCorrelationId() {
    return correlationId;
  }

  public LocalDateTime getTimestamp() {
    return timestamp;
  }
}
