/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package io.portx.ihub.vm.api;

import com.google.common.collect.ImmutableMap;
import org.mule.runtime.api.metadata.TypedValue;
import org.mule.runtime.extension.api.annotation.param.Parameter;

import static java.time.LocalDateTime.now;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Attributes on the message content generated by a VM connector operation
 *
 * @since 1.0
 */
public class VMMessageAttributes implements Serializable {

  private static final long serialVersionUID = 3923721884012142263L;

  /**
   * The name of the queue the content came from.
   */
  private final String queueName;

  /**
   * The correlation id for the message
   */
  private final String correlationId;

  /**
   * The time at which the content was retrieved.
   */
  private final LocalDateTime timestamp = now();

  /**
   * Message properties
   */
  @Parameter
  private final Map<String, TypedValue<Serializable>> properties;

  /**
   * Creates a new instance
   *
   * @param queueName     the name of the queue from which the message was taken
   * @param correlationId the message correlation id
   */
  public VMMessageAttributes(String queueName, String correlationId) {
    this(queueName, correlationId, new HashMap<>());
  }

  /**
   * Creates a new instance
   *
   * @param queueName     the name of the queue from which the message was taken
   * @param correlationId the message correlation id
   * @param properties    optional map of message properties
   */
  public VMMessageAttributes(String queueName, String correlationId, Map<String, TypedValue<Serializable>> properties) {
    this.queueName = queueName;
    this.correlationId = correlationId;
    this.properties = properties;
  }

  public String getQueueName() {
    return queueName;
  }

  public String getCorrelationId() {
    return correlationId;
  }

  public LocalDateTime getTimestamp() {
    return timestamp;
  }

  public Map<String, TypedValue<Serializable>> getProperties() {
    return ImmutableMap.copyOf(this.properties);
  }
}
